# Generated by Django 3.2 on 2021-04-30 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meraki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerakiNetworks',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('organizationId', models.CharField(max_length=200)),
                ('productTypes', models.CharField(max_length=200)),
                ('timeZone', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
