# Generated by Django 3.2 on 2021-04-30 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meraki', '0002_merakinetworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerakiDevices',
            fields=[
                ('serial', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('mac', models.CharField(max_length=200)),
                ('lanIp', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200)),
                ('networkId', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('firmware', models.CharField(max_length=200)),
                ('wan1Ip', models.CharField(max_length=200, null=True)),
                ('wan2Ip', models.CharField(max_length=200, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
