# Generated by Django 3.2 on 2021-05-05 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dcnm_network_device',
            fields=[
                ('dcnm_addr', models.CharField(max_length=200)),
                ('asn', models.CharField(max_length=200)),
                ('deviceType', models.CharField(max_length=200)),
                ('fabricId', models.CharField(max_length=200)),
                ('fabricName', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('fabricTechnology', models.CharField(max_length=200)),
                ('fabricType', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=200)),
                ('networkTemplate', models.CharField(max_length=200)),
                ('ADVERTISE_PIP_BGP', models.CharField(max_length=200)),
                ('ANYCAST_GW_MAC', models.CharField(max_length=200)),
                ('ANYCAST_RP_IP_RANGE', models.CharField(max_length=200)),
                ('BFD_ENABLE', models.CharField(max_length=200)),
                ('BFD_AUTH_ENABLE', models.CharField(max_length=200)),
                ('BGP_AS', models.CharField(max_length=200)),
                ('BGP_AUTH_ENABLE', models.CharField(max_length=200)),
                ('DCI_SUBNET_RANGE', models.CharField(max_length=200)),
                ('DCI_SUBNET_TARGET_MASK', models.CharField(max_length=200)),
                ('DHCP_ENABLE', models.CharField(max_length=200)),
                ('ENABLE_EVPN', models.CharField(max_length=200)),
                ('ENABLE_NXAPI', models.CharField(max_length=200)),
                ('FABRIC_INTERFACE_TYPE', models.CharField(max_length=200)),
                ('FABRIC_MTU', models.CharField(max_length=200)),
                ('FABRIC_NAME', models.CharField(max_length=200)),
                ('L2_SEGMENT_ID_RANGE', models.CharField(max_length=200)),
                ('L3_PARTITION_ID_RANGE', models.CharField(max_length=200)),
                ('LINK_STATE_ROUTING', models.CharField(max_length=200)),
                ('LINK_STATE_ROUTING_TAG', models.CharField(max_length=200)),
                ('LOOPBACK0_IP_RANGE', models.CharField(max_length=200)),
                ('LOOPBACK1_IP_RANGE', models.CharField(max_length=200)),
                ('MULTICAST_GROUP_SUBNET', models.CharField(max_length=200)),
                ('NETWORK_VLAN_RANGE', models.CharField(max_length=200)),
                ('OSPF_AREA_ID', models.CharField(max_length=200)),
                ('OSPF_AUTH_ENABLE', models.CharField(max_length=200)),
                ('REPLICATION_MODE', models.CharField(max_length=200)),
                ('RR_COUNT', models.CharField(max_length=200)),
                ('SERVICE_NETWORK_VLAN_RANGE', models.CharField(max_length=200)),
                ('SUBNET_RANGE', models.CharField(max_length=200)),
                ('replicationMode', models.CharField(max_length=200)),
                ('templateName', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='dcnm_network_switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcnm_addr', models.CharField(max_length=200)),
                ('activeSupSlot', models.CharField(max_length=200)),
                ('availPorts', models.IntegerField()),
                ('consistencyState', models.CharField(max_length=200)),
                ('cpuUsage', models.IntegerField()),
                ('fabricName', models.CharField(max_length=200)),
                ('health', models.IntegerField()),
                ('hostName', models.CharField(max_length=200)),
                ('ipAddress', models.CharField(max_length=200)),
                ('isVpcConfigured', models.CharField(max_length=200)),
                ('keepAliveState', models.CharField(default='None', max_length=200)),
                ('licenseDetail', models.CharField(max_length=200)),
                ('licenseViolation', models.CharField(max_length=200)),
                ('logicalName', models.CharField(max_length=200)),
                ('managable', models.CharField(max_length=200)),
                ('memoryUsage', models.CharField(max_length=200)),
                ('mode', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('network', models.CharField(max_length=200)),
                ('numberOfPorts', models.CharField(max_length=200)),
                ('peer', models.CharField(max_length=200)),
                ('present', models.CharField(max_length=200)),
                ('release', models.CharField(max_length=200)),
                ('serialNumber', models.CharField(max_length=200)),
                ('upTime', models.BigIntegerField()),
                ('vendor', models.CharField(max_length=200)),
                ('vpcDomain', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
