# Generated by Django 3.2 on 2021-05-17 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sdwan_deviceCounters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crashCount', models.IntegerField()),
                ('expectedControlConnections', models.IntegerField()),
                ('number_vsmart_control_connections', models.IntegerField()),
                ('rebootCount', models.IntegerField()),
                ('systemIp', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
