# Generated by Django 3.2 on 2021-05-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan', '0002_sdwan_devicecounters'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdwan_devicecounters',
            name='bfdSessionsDown',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sdwan_devicecounters',
            name='bfdSessionsUp',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sdwan_devicecounters',
            name='ompPeersDown',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sdwan_devicecounters',
            name='ompPeersUp',
            field=models.IntegerField(default=None),
        ),
    ]
